### PR TITLE
templates/header.html: Commented out jQuery for now; whitespace

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by elimisteve** [comment]
@medvednikov How about you import `/jquery.js` just into `tree.html` as mentioned on Discord, then merge this?

**Comment by medvednikov** [comment]
You should add jquery to tree.html in this PR

**Comment by medvednikov** [comment]
well ok i'll do it

**Comment by medvednikov** [comment]
I fixed it in a different commit.

**Comment by elimisteve** [comment]
@medvednikov Cool :+1:

**Pull request closed without merging**
