### PR TITLE
Fix compilation with latest v

### PR DESCRIPTION
**Pull request by spytheman**
This PR fixes compilation with V 0.1.28 2284865

### CODE REVIEW

**Comment by elimisteve** [comment]
I like the `http.Method` type and internally using enums makes sense for performance reasons, but maybe `http.new_request` should accept a string rather than making users type `http.Method.get` and the like.

**Comment by spytheman** [comment]
users can call http.get instead

**Comment by elimisteve** [comment]
For simple `GET` requests, yes, but that doesn't help those who want or need to call `http.new_request`.

**Comment by spytheman** [comment]
Thanks to v's cleverness ;-) it can be shortened to just `.get` which is both shorter and safer than 'GET' :-)

**Comment by elimisteve** [comment]
Damn that's fucking awesome lol

**Pull request merged**
